In [1]:
import pandas as pd

In [8]:
dados = pd.read_json('informacoes.json')
dados

   nome  idade                                          enderecos
0  João     28  {'tipo': 'casa', 'rua': 'Rua A', 'numero': 123...
1  João     28  {'tipo': 'trabalho', 'rua': 'Rua B', 'numero':...

In [16]:
import json

with open('informacoes.json') as f:
    dados = json.load(f)

informacoes = pd.json_normalize(data=dados, record_path='enderecos', meta=['nome', 'idade'], errors='ignore')

In [17]:
informacoes

       tipo    rua  numero          cidade   nome idade
0      casa  Rua A     123      SÃ£o Paulo  JoÃ£o    28
1  trabalho  Rua B     456  Rio de Janeiro  JoÃ£o    28

In [1]:
import pandas as pd
import json

In [20]:
with open('dados.json', 'r') as f:
    dados = json.load(f)

In [26]:
dados = pd.json_normalize(dados, record_path=['pessoas'])

In [30]:
dados['idade'] = dados['idade'].astype(int)

In [ ]:
dados['telefones'] = dados['telefones'].astype(str)

In [35]:
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nome             2 non-null      str
 1   idade            2 non-null      int64
 2   telefones        2 non-null      str
 3   endereco.rua     2 non-null      str
 4   endereco.numero  2 non-null      int64
 5   endereco.cidade  2 non-null      str
dtypes: int64(2), str(4)
memory usage: 228.0 bytes

In [34]:
dados.head()

,nome,idade,telefones,endereco.rua,endereco.numero,endereco.cidade
0,JoÃ£o,25,"['11 1111-1111', '11 2222-2222']",Rua A,123,SÃ£o Paulo
1,Maria,30,['21 3333-3333'],,456,Rio de Janeiro

In [45]:
dado_vazio = dados[dados['endereco.rua'] == ''].copy()

In [53]:
df_filtrado = dados[dados['endereco.rua'] != ""]

In [54]:
df_filtrado

,nome,idade,telefones,endereco.rua,endereco.numero,endereco.cidade
0,JoÃ£o,25,"['11 1111-1111', '11 2222-2222']",Rua A,123,SÃ£o Paulo