In [2]:
import pandas as pd

In [3]:
dados = pd.read_json('informacoes.json')
dados

   nome  idade                                          enderecos
0  João     28  {'tipo': 'casa', 'rua': 'Rua A', 'numero': 123...
1  João     28  {'tipo': 'trabalho', 'rua': 'Rua B', 'numero':...

In [4]:
import json

with open('informacoes.json') as f:
    dados = json.load(f)

informacoes = pd.json_normalize(data=dados, record_path='enderecos', meta=['nome', 'idade'], errors='ignore')

In [5]:
informacoes

       tipo    rua  numero          cidade   nome idade
0      casa  Rua A     123      SÃ£o Paulo  JoÃ£o    28
1  trabalho  Rua B     456  Rio de Janeiro  JoÃ£o    28

In [6]:
import pandas as pd
import json

In [7]:
with open('dados.json', 'r') as f:
    dados = json.load(f)

In [8]:
dados = pd.json_normalize(dados, record_path=['pessoas'])

In [9]:
dados['idade'] = dados['idade'].astype(int)

In [10]:
dados['telefones'] = dados['telefones'].astype(str)

In [11]:
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   nome             2 non-null      str
 1   idade            2 non-null      int64
 2   telefones        2 non-null      str
 3   endereco.rua     2 non-null      str
 4   endereco.numero  2 non-null      int64
 5   endereco.cidade  2 non-null      str
dtypes: int64(2), str(4)
memory usage: 228.0 bytes

In [12]:
dados.head()

,nome,idade,telefones,endereco.rua,endereco.numero,endereco.cidade
0,JoÃ£o,25,"['11 1111-1111', '11 2222-2222']",Rua A,123,SÃ£o Paulo
1,Maria,30,['21 3333-3333'],,456,Rio de Janeiro

In [13]:
dado_vazio = dados[dados['endereco.rua'] == ''].copy()

In [14]:
df_filtrado = dados[dados['endereco.rua'] != ""]

In [15]:
df_filtrado

,nome,idade,telefones,endereco.rua,endereco.numero,endereco.cidade
0,JoÃ£o,25,"['11 1111-1111', '11 2222-2222']",Rua A,123,SÃ£o Paulo

<p>Exercicios aula 3</p>

In [16]:
import pandas as pd
import json

In [17]:
cursos = pd.read_json('cursos_cadastrados.json')

In [18]:
with open('cursos_cadastrados.json', 'r', encoding='utf-8') as f:
    cursos = json.load(f)

In [19]:
cursos = pd.json_normalize(cursos)

In [20]:
cursos.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   curso               6 non-null      str
 1   categoria           6 non-null      str
 2   carga_horaria       5 non-null      str
 3   concluintes         5 non-null      object
 4   data_inicio         5 non-null      str
 5   data_conclusao      5 non-null      str
 6   descricao           5 non-null      str
 7   preco               5 non-null      object
 8   instrutor.nome      6 non-null      str
 9   instrutor.email     6 non-null      str
 10  instrutor.telefone  6 non-null      str
dtypes: object(2), str(9)
memory usage: 660.0+ bytes

In [21]:
cursos['carga_horaria'] = cursos['carga_horaria'].fillna('10 horas', inplace=True)

C:\Users\eneto\AppData\Local\Temp\ipykernel_11112\1449180771.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  cursos['carga_horaria'] = cursos['carga_horaria'].fillna('10 horas', inplace=True)

In [22]:
cursos['descricao'] = cursos['descricao'].fillna('Curso introdutório para Excel.')

In [23]:
cursos

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
0,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999
1,Excel para iniciantes,Produtividade,10 horas,None,NaN,NaN,Curso introdutório para Excel.,None,Maria Oliveira,maria.oliveira@emailaleatorio.com,(11) 8888-8888
2,Marketing digital para negócios,Marketing,30 horas,75,2022-03-01,2022-03-31,Curso introdutório em marketing,89.9,Ana Santos,ana.santos@emailaleatorio.com,(11) 7777-7777
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,,contato@emailaleatorio.com,
4,Inglês para negócios,Idiomas,20 horas,30,,,Curso de inglês para negócios,69.9,John Smith,,
5,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999

In [24]:
cursos.at[3, "instrutor.nome"] = 'Teste'
cursos

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
0,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999
1,Excel para iniciantes,Produtividade,10 horas,None,NaN,NaN,Curso introdutório para Excel.,None,Maria Oliveira,maria.oliveira@emailaleatorio.com,(11) 8888-8888
2,Marketing digital para negócios,Marketing,30 horas,75,2022-03-01,2022-03-31,Curso introdutório em marketing,89.9,Ana Santos,ana.santos@emailaleatorio.com,(11) 7777-7777
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,Teste,contato@emailaleatorio.com,
4,Inglês para negócios,Idiomas,20 horas,30,,,Curso de inglês para negócios,69.9,John Smith,,
5,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999

In [39]:
cursos['preco'].isna()
cursos['preco'] = cursos['preco'].fillna(79.90)
cursos.head()

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone,precos
0,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999,<bound method NDFrame.copy of 0 99.90\n1 ...
1,Excel para iniciantes,Produtividade,10 horas,None,NaN,NaN,Curso introdutório para Excel.,79.9,Maria Oliveira,maria.oliveira@emailaleatorio.com,(11) 8888-8888,<bound method NDFrame.copy of 0 99.90\n1 ...
2,Marketing digital para negócios,Marketing,30 horas,75,2022-03-01,2022-03-31,Curso introdutório em marketing,89.9,Ana Santos,ana.santos@emailaleatorio.com,(11) 7777-7777,<bound method NDFrame.copy of 0 99.90\n1 ...
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,Teste,contato@emailaleatorio.com,,<bound method NDFrame.copy of 0 99.90\n1 ...
4,Inglês para negócios,Idiomas,20 horas,30,,,Curso de inglês para negócios,69.9,John Smith,,,<bound method NDFrame.copy of 0 99.90\n1 ...

In [51]:
cursos['concluintes'] = cursos['concluintes'].fillna(80)
cursos['data_inicio'] = cursos['data_inicio'].fillna('2022-03-22')
cursos['data_conclusao'] = cursos['data_conclusao'].fillna('2022-04-16')

In [52]:
cursos

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone,precos
0,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999,<bound method NDFrame.copy of 0 99.90\n1 ...
1,Excel para iniciantes,Produtividade,10 horas,80,2022-03-22,2022-04-16,Curso introdutório para Excel.,79.9,Maria Oliveira,maria.oliveira@emailaleatorio.com,(11) 8888-8888,<bound method NDFrame.copy of 0 99.90\n1 ...
2,Marketing digital para negócios,Marketing,30 horas,75,2022-03-01,2022-03-31,Curso introdutório em marketing,89.9,Ana Santos,ana.santos@emailaleatorio.com,(11) 7777-7777,<bound method NDFrame.copy of 0 99.90\n1 ...
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,Teste,contato@emailaleatorio.com,,<bound method NDFrame.copy of 0 99.90\n1 ...
4,Inglês para negócios,Idiomas,20 horas,30,,,Curso de inglês para negócios,69.9,John Smith,,,<bound method NDFrame.copy of 0 99.90\n1 ...
5,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999,<bound method NDFrame.copy of 0 99.90\n1 ...

In [55]:
cursos.head()

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone,precos
0,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999,<bound method NDFrame.copy of 0 99.90\n1 ...
1,Excel para iniciantes,Produtividade,10 horas,80,2022-03-22,2022-04-16,Curso introdutório para Excel.,79.9,Maria Oliveira,maria.oliveira@emailaleatorio.com,(11) 8888-8888,<bound method NDFrame.copy of 0 99.90\n1 ...
2,Marketing digital para negócios,Marketing,30 horas,75,2022-03-01,2022-03-31,Curso introdutório em marketing,89.9,Ana Santos,ana.santos@emailaleatorio.com,(11) 7777-7777,<bound method NDFrame.copy of 0 99.90\n1 ...
3,Inteligência artificial,Programação,40 horas,,2022-04-01,,Curso avançado sobre inteligência artificial c...,129.9,Teste,contato@emailaleatorio.com,,<bound method NDFrame.copy of 0 99.90\n1 ...
4,Inglês para negócios,Idiomas,20 horas,30,,,Curso de inglês para negócios,69.9,John Smith,,,<bound method NDFrame.copy of 0 99.90\n1 ...

In [59]:
cursos.at[3, "concluintes"] = 92
cursos.at[3, 'data_conclusao'] = '2022-04-26'
cursos.at[3, "instrutor.telefone"] = '(11) 6666-6666'

cursos.at[4, "data_inicio"] = '2022-07-18'
cursos.at[4, "data_conclusao"] = '2022-08-01'
cursos.at[4, "instrutor.email"] = 'testeteste@gmail.com'
cursos.at[4, "instrutor_telefone"] = '(11) 5555-5555'

In [61]:
cursos.at[4, 'instrutor.telefone'] = '(11) 5555-5555'
cursos

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone,precos,instrutor_telefone
0,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999,<bound method NDFrame.copy of 0 99.90\n1 ...,NaN
1,Excel para iniciantes,Produtividade,10 horas,80,2022-03-22,2022-04-16,Curso introdutório para Excel.,79.9,Maria Oliveira,maria.oliveira@emailaleatorio.com,(11) 8888-8888,<bound method NDFrame.copy of 0 99.90\n1 ...,NaN
2,Marketing digital para negócios,Marketing,30 horas,75,2022-03-01,2022-03-31,Curso introdutório em marketing,89.9,Ana Santos,ana.santos@emailaleatorio.com,(11) 7777-7777,<bound method NDFrame.copy of 0 99.90\n1 ...,NaN
3,Inteligência artificial,Programação,40 horas,92,2022-04-01,2022-04-26,Curso avançado sobre inteligência artificial c...,129.9,Teste,contato@emailaleatorio.com,(11) 6666-6666,<bound method NDFrame.copy of 0 99.90\n1 ...,NaN
4,Inglês para negócios,Idiomas,20 horas,30,2022-07-18,2022-08-01,Curso de inglês para negócios,69.9,John Smith,testeteste@gmail.com,(11) 5555-5555,<bound method NDFrame.copy of 0 99.90\n1 ...,(11) 5555-5555
5,Introdução à programação,Programação,20 horas,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.90,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999,<bound method NDFrame.copy of 0 99.90\n1 ...,NaN

In [68]:
cursos['carga_horaria'].values

array([list(['20']), list(['10']), list(['30']), list(['40']),
       list(['20']), list(['20'])], dtype=object)

In [71]:
cursos['carga_horaria'] = cursos['carga_horaria'].explode()

In [76]:
cursos['carga_horaria'] = cursos['carga_horaria'].astype(int)

In [77]:
cursos['carga_horaria'].values

array([20, 10, 30, 40, 20, 20])

In [83]:
cursos['concluintes'] = cursos['concluintes'].astype(int)
cursos.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   curso               6 non-null      str
 1   categoria           6 non-null      str
 2   carga_horaria       6 non-null      int64
 3   concluintes         6 non-null      int64
 4   data_inicio         6 non-null      str
 5   data_conclusao      6 non-null      str
 6   descricao           6 non-null      str
 7   preco               6 non-null      object
 8   instrutor.nome      6 non-null      str
 9   instrutor.email     6 non-null      str
 10  instrutor.telefone  6 non-null      str
 11  precos              6 non-null      object
 12  instrutor_telefone  1 non-null      str
dtypes: int64(2), object(2), str(9)
memory usage: 756.0+ bytes

In [86]:
cursos['data_inicio'] = cursos['data_inicio'].astype('datetime64[us]')
cursos['data_conclusao'] = cursos['data_conclusao'].astype('datetime64[us]')

In [89]:
cursos.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   curso               6 non-null      str
 1   categoria           6 non-null      str
 2   carga_horaria       6 non-null      int64
 3   concluintes         6 non-null      int64
 4   data_inicio         6 non-null      datetime64[us]
 5   data_conclusao      6 non-null      datetime64[us]
 6   descricao           6 non-null      str
 7   preco               6 non-null      object
 8   instrutor.nome      6 non-null      str
 9   instrutor.email     6 non-null      str
 10  instrutor.telefone  6 non-null      str
 11  precos              6 non-null      object
 12  instrutor_telefone  1 non-null      str
dtypes: datetime64[us](2), int64(2), object(2), str(7)
memory usage: 756.0+ bytes

In [90]:
cursos['preco'].values

array(['99.90', 79.9, 89.9, 129.9, 69.9, '99.90'], dtype=object)

In [99]:
cursos['preco'] = pd.to_numeric(cursos['preco'])
cursos['preco'].values
cursos['preco'] = cursos['preco'].astype(float)
cursos.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   curso               6 non-null      str
 1   categoria           6 non-null      str
 2   carga_horaria       6 non-null      int64
 3   concluintes         6 non-null      int64
 4   data_inicio         6 non-null      datetime64[us]
 5   data_conclusao      6 non-null      datetime64[us]
 6   descricao           6 non-null      str
 7   preco               6 non-null      float64
 8   instrutor.nome      6 non-null      str
 9   instrutor.email     6 non-null      str
 10  instrutor.telefone  6 non-null      str
 11  precos              6 non-null      object
 12  instrutor_telefone  1 non-null      str
dtypes: datetime64[us](2), float64(1), int64(2), object(1), str(7)
memory usage: 756.0+ bytes

In [103]:
cursos

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone,precos,instrutor_telefone
0,Introdução à programação,Programação,20,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.9,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999,<bound method NDFrame.copy of 0 99.90\n1 ...,NaN
1,Excel para iniciantes,Produtividade,10,80,2022-03-22,2022-04-16,Curso introdutório para Excel.,79.9,Maria Oliveira,maria.oliveira@emailaleatorio.com,(11) 8888-8888,<bound method NDFrame.copy of 0 99.90\n1 ...,NaN
2,Marketing digital para negócios,Marketing,30,75,2022-03-01,2022-03-31,Curso introdutório em marketing,89.9,Ana Santos,ana.santos@emailaleatorio.com,(11) 7777-7777,<bound method NDFrame.copy of 0 99.90\n1 ...,NaN
3,Inteligência artificial,Programação,40,92,2022-04-01,2022-04-26,Curso avançado sobre inteligência artificial c...,129.9,Teste,contato@emailaleatorio.com,(11) 6666-6666,<bound method NDFrame.copy of 0 99.90\n1 ...,NaN
4,Inglês para negócios,Idiomas,20,30,2022-07-18,2022-08-01,Curso de inglês para negócios,69.9,John Smith,testeteste@gmail.com,(11) 5555-5555,<bound method NDFrame.copy of 0 99.90\n1 ...,(11) 5555-5555
5,Introdução à programação,Programação,20,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.9,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999,<bound method NDFrame.copy of 0 99.90\n1 ...,NaN

In [110]:
cursos_clean = cursos

In [117]:
cursos_clean.drop(['instrutor_telefone'],axis=1, inplace=True)

In [118]:
cursos_clean

,curso,categoria,carga_horaria,concluintes,data_inicio,data_conclusao,descricao,preco,instrutor.nome,instrutor.email,instrutor.telefone
0,Introdução à programação,Programação,20,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.9,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999
1,Excel para iniciantes,Produtividade,10,80,2022-03-22,2022-04-16,Curso introdutório para Excel.,79.9,Maria Oliveira,maria.oliveira@emailaleatorio.com,(11) 8888-8888
2,Marketing digital para negócios,Marketing,30,75,2022-03-01,2022-03-31,Curso introdutório em marketing,89.9,Ana Santos,ana.santos@emailaleatorio.com,(11) 7777-7777
3,Inteligência artificial,Programação,40,92,2022-04-01,2022-04-26,Curso avançado sobre inteligência artificial c...,129.9,Teste,contato@emailaleatorio.com,(11) 6666-6666
4,Inglês para negócios,Idiomas,20,30,2022-07-18,2022-08-01,Curso de inglês para negócios,69.9,John Smith,testeteste@gmail.com,(11) 5555-5555
5,Introdução à programação,Programação,20,100,2022-01-01,2022-01-20,Curso introdutório à programação com Python,99.9,João Silva,joao.silva@emailaleatorio.com,(11) 9999-9999

In [119]:
cursos_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   curso               6 non-null      str
 1   categoria           6 non-null      str
 2   carga_horaria       6 non-null      int64
 3   concluintes         6 non-null      int64
 4   data_inicio         6 non-null      datetime64[us]
 5   data_conclusao      6 non-null      datetime64[us]
 6   descricao           6 non-null      str
 7   preco               6 non-null      float64
 8   instrutor.nome      6 non-null      str
 9   instrutor.email     6 non-null      str
 10  instrutor.telefone  6 non-null      str
dtypes: datetime64[us](2), float64(1), int64(2), str(6)
memory usage: 660.0 bytes