<h2>Creating the DF</h2>

In [3]:
import pandas as pd

values = {"Maça":[2.50], "Banana":[1.20], "Uva":[4.00]}
df = pd.DataFrame(values)

In [5]:
df.T

          0
Maça    2.5
Banana  1.2
Uva     4.0

In [11]:
values_2 = {"Fruta":["Maça", "Banana", "Uva"],
            "Preço":[2.50, 1.20, 4.00]}
df_correta = pd.DataFrame(values_2)

In [10]:
df_correta

    Fruta  Preço
0    Maça    2.5
1  Banana    1.2
2     Uva    4.0

<h2>Filtragem de dados</h2>

In [18]:
df_correta['Preço'].min()

np.float64(1.2)

In [20]:
df_correta[df_correta['Preço'] > 3.0]

  Fruta  Preço
2   Uva    4.0

<h2>Adição de elemento</h2>

In [21]:
df_correta['Quantidade'] = [3, 5, 2]

In [22]:
df_correta

    Fruta  Preço  Quantidade
0    Maça    2.5           3
1  Banana    1.2           5
2     Uva    4.0           2

<h2>Operações Matemáticas entre Colunas</h2>

In [23]:
resultado_multiplicacao = df_correta['Preço'] * df_correta['Quantidade']

In [24]:
df_correta['Total'] = resultado_multiplicacao

In [25]:
df_correta

    Fruta  Preço  Quantidade  Total
0    Maça    2.5           3    7.5
1  Banana    1.2           5    6.0
2     Uva    4.0           2    8.0

<h2>Ordenar os dados</h2>

In [29]:
df_correta.sort_values(by='Total', ascending=False)

    Fruta  Preço  Quantidade  Total
2     Uva    4.0           2    8.0
0    Maça    2.5           3    7.5
1  Banana    1.2           5    6.0

<h2>Resumos Estatísticos</h2>

In [30]:
df_correta.describe()

          Preço  Quantidade     Total
count  3.000000    3.000000  3.000000
mean   2.566667    3.333333  7.166667
std    1.401190    1.527525  1.040833
min    1.200000    2.000000  6.000000
25%    1.850000    2.500000  6.750000
50%    2.500000    3.000000  7.500000
75%    3.250000    4.000000  7.750000
max    4.000000    5.000000  8.000000

In [31]:
df_correta.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Fruta       3 non-null      str
 1   Preço       3 non-null      float64
 2   Quantidade  3 non-null      int64
 3   Total       3 non-null      float64
dtypes: float64(2), int64(1), str(1)
memory usage: 228.0 bytes

<h2>Lidar com Dados Ausentes</h2>

In [32]:
df_correta.dropna()

    Fruta  Preço  Quantidade  Total
0    Maça    2.5           3    7.5
1  Banana    1.2           5    6.0
2     Uva    4.0           2    8.0

In [34]:
df_correta.fillna(0)

    Fruta  Preço  Quantidade  Total
0    Maça    2.5           3    7.5
1  Banana    1.2           5    6.0
2     Uva    4.0           2    8.0

<h2>Agrupamento de Dados</h2>

In [43]:
agrupamento_dados = df_correta.groupby(['Fruta'])[['Preço', 'Quantidade', 'Total']].sum().sort_values(by='Total', ascending=False)

In [44]:
agrupamento_dados

        Preço  Quantidade  Total
Fruta
Uva       4.0           2    8.0
Maça      2.5           3    7.5
Banana    1.2           5    6.0

In [47]:
agrupamento_dados_preço = df_correta.groupby(['Fruta'])[['Preço']].sum().sort_values(by='Preço', ascending=False)
agrupamento_dados_preço

        Preço
Fruta
Uva       4.0
Maça      2.5
Banana    1.2

In [ ]:
df_correta.groupby(['Fruta', 'Preço'])

In [48]:
df_correta.groupby(['Fruta', 'Preço'])[['Quantidade']].sum()

              Quantidade
Fruta  Preço
Banana 1.2             5
Maça   2.5             3
Uva    4.0             2

In [54]:
df_correta.groupby('Fruta').agg({'Quantidade': 'sum', 'Preço': 'mean'}).sort_values(by='Preço', ascending=False).index

Index(['Uva', 'Maça', 'Banana'], dtype='str', name='Fruta')

In [55]:
df_correta.groupby('Fruta').agg({'Quantidade': 'sum', 'Preço': 'mean'}).sort_values(by='Preço', ascending=False).reset_index()

    Fruta  Quantidade  Preço
0     Uva           2    4.0
1    Maça           3    2.5
2  Banana           5    1.2

In [ ]:
df_correta.filter()