<h3>First exercise</h3>

To take a raw dataset and be able to slice it in every possible way without looking at the documentation.

In [1]:
import pandas as pd

In [10]:
dados = {
    'Nome': ['Jorge', 'Giuberto', 'Renan', 'Pedro'],
    'Turma': ['Terceiro', 'Terceiro', 'Terceiro', 'Segundo'],
    'Notas': [6.7, 8.5, 9.0, 7.5]
}

df = pd.DataFrame(dados)

In [13]:
dados_brutos = {
    'Vendedor': ['Ana', 'Bruno', 'Ana', 'Carlos', 'Bruno', 'Ana', 'Carlos', 'Carlos'],
    'Produto': ['Celular', 'Fone', 'Celular', 'Tablet', 'Fone', 'Tablet', 'Celular', 'Tablet'],
    'Vendas_R$': [2500, 150, 2500, 1200, 150, 1100, 2500, 1300],
    'Data': ['2024-01-05', '2024-01-05', '2024-01-06', '2024-01-06', '2024-01-07', '2024-01-07', '2024-01-08', '2024-01-08'],
    'Comissao_%': [10, 5, 10, 8, 5, 8, 10, 8]
}

df_vendas = pd.DataFrame(dados_brutos)
df_vendas

  Vendedor  Produto  Vendas_R$        Data  Comissao_%
0      Ana  Celular       2500  2024-01-05          10
1    Bruno     Fone        150  2024-01-05           5
2      Ana  Celular       2500  2024-01-06          10
3   Carlos   Tablet       1200  2024-01-06           8
4    Bruno     Fone        150  2024-01-07           5
5      Ana   Tablet       1100  2024-01-07           8
6   Carlos  Celular       2500  2024-01-08          10
7   Carlos   Tablet       1300  2024-01-08           8

In [22]:
df_vendas.groupby(by=["Vendedor"], group_keys=True)['Vendas_R$'].sum()

Vendedor
Ana       6100
Bruno      300
Carlos    5000
Name: Vendas_R$, dtype: int64

In [25]:
df_vendas['Produto'].value_counts()

Produto
Celular    3
Tablet     3
Fone       2
Name: count, dtype: int64

In [ ]:
df_vendas

  Vendedor  Produto  Vendas_R$        Data  Comissao_%  Soma_venda_individual
0      Ana  Celular       2500  2024-01-05          10                    NaN
1    Bruno     Fone        150  2024-01-05           5                    NaN
2      Ana  Celular       2500  2024-01-06          10                    NaN
3   Carlos   Tablet       1200  2024-01-06           8                    NaN
4    Bruno     Fone        150  2024-01-07           5                    NaN
5      Ana   Tablet       1100  2024-01-07           8                    NaN
6   Carlos  Celular       2500  2024-01-08          10                    NaN
7   Carlos   Tablet       1300  2024-01-08           8                    NaN

In [ ]:
colunas = df_vendas.columns

Index(['Vendedor', 'Produto', 'Vendas_R$', 'Data', 'Comissao_%',
       'Soma_venda_individual'],
      dtype='str')

In [38]:
df_vendas_vendedores = df_vendas.groupby('Vendedor')['Vendas_R$'].agg({"sum", "mean"})

In [39]:
df_vendas_vendedores.reset_index(inplace=True, drop=True)

In [40]:
df_vendas_vendedores

    sum         mean
0  6100  2033.333333
1   300   150.000000
2  5000  1666.666667

In [63]:
df_vendas = df_vendas.rename(columns={"Vendas_R$": "Vendas_reais"})

In [64]:
df_vendas

,Vendedor,Produto,Vendas_reais,Data,Comissao_%,Soma_venda_individual
0,Ana,Celular,2500,2024-01-05,10,NaN
1,Bruno,Fone,150,2024-01-05,5,NaN
2,Ana,Celular,2500,2024-01-06,10,NaN
3,Carlos,Tablet,1200,2024-01-06,8,NaN
4,Bruno,Fone,150,2024-01-07,5,NaN
5,Ana,Tablet,1100,2024-01-07,8,NaN
6,Carlos,Celular,2500,2024-01-08,10,NaN
7,Carlos,Tablet,1300,2024-01-08,8,NaN

In [65]:
df_vendas.query("Vendas_reais > 1500")

,Vendedor,Produto,Vendas_reais,Data,Comissao_%,Soma_venda_individual
0,Ana,Celular,2500,2024-01-05,10,NaN
2,Ana,Celular,2500,2024-01-06,10,NaN
6,Carlos,Celular,2500,2024-01-08,10,NaN