In [32]:
import pandas as pd

In [33]:
path2 = 'dados_locacao_imoveis.json'

dados2 = pd.read_json(path2)
dados2 = pd.json_normalize(dados2['dados_locacao'])
dados2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

In [34]:
path = 'dados_vendas_clientes.json'

dados = pd.read_json(path)
dados = pd.json_normalize(dados['dados_vendas'])
dados

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

<h2>Atividade 2</h2>

In [35]:
import pandas as pd
import numpy as np

# Posiciona todas as colunas em uma lista
colunas = list(dados.columns)

In [36]:
dados = dados.explode(colunas[1:])
dados.reset_index(inplace=True, drop=True)
dados

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321        R$ 836,5
1     06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2     06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3     06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4     07/06/2022  Isabely JOanes 738       R$ 825,31
5     07/06/2022  Isabely JOanes 738       R$ 168,07
6     07/06/2022  Isabely JOanes 738       R$ 339,18
7     07/06/2022  Isabely JOanes 738       R$ 314,69
8     08/06/2022  Isabely JOanes 738       R$ 682,05
9     08/06/2022    JOãO Gabriel 671       R$ 386,34
10    08/06/2022  Julya meireles 914       R$ 622,65
11    08/06/2022  Julya meireles 914       R$ 630,79
12    09/06/2022  Julya meireles 914        R$ 390,3
13    09/06/2022     MaRIA Julia 444       R$ 759,16
14    09/06/2022     MaRIA Julia 444       R$ 334,47
15    09/06/2022     MaRIA Julia 444       R$ 678,78
16    10/06/2022     MaRIA Julia 444       R$ 314,24
17    10/06/2022     PEDRO PASCO 812       R$ 311,15
18    10/06/2022    Paulo castro 481       R$ 899,16
19    10/06/2022   Thiago fritzz 883       R$ 885,24

In [37]:
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     str
 1   Cliente          20 non-null     str
 2   Valor da compra  20 non-null     str
dtypes: str(3)
memory usage: 612.0 bytes

In [38]:
dados['Valor da compra'] = dados['Valor da compra'].apply(lambda x: x.replace('R$', '').replace(',', ''))
dados

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321            8365
1     06/06/2022  DieGO ARMANDIU 210           57333
2     06/06/2022  DieGO ARMANDIU 210            3928
3     06/06/2022  DieGO ARMANDIU 210           51234
4     07/06/2022  Isabely JOanes 738           82531
5     07/06/2022  Isabely JOanes 738           16807
6     07/06/2022  Isabely JOanes 738           33918
7     07/06/2022  Isabely JOanes 738           31469
8     08/06/2022  Isabely JOanes 738           68205
9     08/06/2022    JOãO Gabriel 671           38634
10    08/06/2022  Julya meireles 914           62265
11    08/06/2022  Julya meireles 914           63079
12    09/06/2022  Julya meireles 914            3903
13    09/06/2022     MaRIA Julia 444           75916
14    09/06/2022     MaRIA Julia 444           33447
15    09/06/2022     MaRIA Julia 444           67878
16    10/06/2022     MaRIA Julia 444           31424
17    10/06/2022     PEDRO PASCO 812           31115
18    10/06/2022    Paulo castro 481           89916
19    10/06/2022   Thiago fritzz 883           88524

In [39]:
dados['Valor da compra'] = dados['Valor da compra'].astype(float)

In [40]:
dados['Data de venda'] = dados['Data de venda'].astype('datetime64[ns]')

dados.info()
dados

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     datetime64[ns]
 1   Cliente          20 non-null     str
 2   Valor da compra  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), str(1)
memory usage: 612.0 bytes

   Data de venda             Cliente  Valor da compra
0     2022-06-06     @ANA _LUCIA 321           8365.0
1     2022-06-06  DieGO ARMANDIU 210          57333.0
2     2022-06-06  DieGO ARMANDIU 210           3928.0
3     2022-06-06  DieGO ARMANDIU 210          51234.0
4     2022-07-06  Isabely JOanes 738          82531.0
5     2022-07-06  Isabely JOanes 738          16807.0
6     2022-07-06  Isabely JOanes 738          33918.0
7     2022-07-06  Isabely JOanes 738          31469.0
8     2022-08-06  Isabely JOanes 738          68205.0
9     2022-08-06    JOãO Gabriel 671          38634.0
10    2022-08-06  Julya meireles 914          62265.0
11    2022-08-06  Julya meireles 914          63079.0
12    2022-09-06  Julya meireles 914           3903.0
13    2022-09-06     MaRIA Julia 444          75916.0
14    2022-09-06     MaRIA Julia 444          33447.0
15    2022-09-06     MaRIA Julia 444          67878.0
16    2022-10-06     MaRIA Julia 444          31424.0
17    2022-10-06     PEDRO PASCO 812          31115.0
18    2022-10-06    Paulo castro 481          89916.0
19    2022-10-06   Thiago fritzz 883          88524.0

In [41]:
colunas = list(dados2.columns)
colunas

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [42]:
dados2 = dados2.explode(colunas[1:])
dados2.reset_index(inplace=True, drop=True)
dados2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
5,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
6,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
7,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
8,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
9,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
10,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
11,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
12,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
13,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
14,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
15,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
16,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
17,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
18,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
19,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
20,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
21,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
22,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
23,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
24,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
25,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
26,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
27,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
28,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
29,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [43]:
dados2.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     str
 1   datas_combinadas_pagamento  30 non-null     str
 2   datas_de_pagamento          30 non-null     str
 3   valor_aluguel               30 non-null     str
dtypes: str(4)
memory usage: 1.1 KB

In [44]:
dados2[['datas_combinadas_pagamento', 'datas_de_pagamento']] = dados2[['datas_combinadas_pagamento', 'datas_de_pagamento']].astype('datetime64[ns]')

dados2['valor_aluguel'] = dados2['valor_aluguel'].apply(lambda x: x.replace('$', '').replace(',', '').replace('reais', ''))

In [45]:
dados2['valor_aluguel'] = dados2['valor_aluguel'].astype(float)

In [46]:
dados2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),2022-01-06,2022-05-06,10000.0
1,A101 (blocoAP),2022-01-07,2022-03-07,25000.0
2,A102 (blocoAP),2022-02-06,2022-02-06,11000.0
3,A102 (blocoAP),2022-02-07,2022-06-07,26000.0
4,B201 (blocoAP),2022-03-06,2022-07-06,12000.0
5,B201 (blocoAP),2022-03-07,2022-03-07,27000.0
6,B202 (blocoAP),2022-04-06,2022-07-06,13000.0
7,B202 (blocoAP),2022-04-07,2022-05-07,28000.0
8,C301 (blocoAP),2022-05-06,2022-10-06,14000.0
9,C301 (blocoAP),2022-05-07,2022-09-07,29000.0
10,C302 (blocoAP),2022-06-06,2022-08-06,15000.0
11,C302 (blocoAP),2022-06-07,2022-12-07,12000.0
12,D401 (blocoAP),2022-07-06,2022-07-06,16000.0
13,D401 (blocoAP),2022-07-07,2022-09-07,13000.0
14,D402 (blocoAP),2022-08-06,2022-10-06,17000.0
15,D402 (blocoAP),2022-08-07,2022-07-14,14000.0
16,E501 (blocoAP),2022-09-06,2022-10-06,18000.0
17,E501 (blocoAP),2022-09-07,2022-09-07,15000.0
18,E502 (blocoAP),2022-10-06,2022-06-16,19000.0
19,E502 (blocoAP),2022-10-07,2022-12-07,16000.0
20,F601 (blocoAP),2022-11-06,2022-06-17,20000.0
21,F601 (blocoAP),2022-11-07,2022-07-13,10000.0
22,F602 (blocoAP),2022-12-06,2022-06-15,21000.0
23,F602 (blocoAP),2022-12-07,2022-12-07,11000.0
24,G701 (blocoAP),2022-06-13,2022-06-19,22000.0
25,G701 (blocoAP),2022-07-13,2022-07-20,12000.0
26,G702 (blocoAP),2022-06-14,2022-06-15,23000.0
27,G702 (blocoAP),2022-07-14,2022-07-17,21000.0
28,H801 (blocoAP),2022-06-15,2022-06-18,24000.0
29,H801 (blocoAP),2022-07-15,2022-07-16,22000.0

<h2>Atividades Aula 3</h2>

In [47]:
path3 = 'dados_hospedagem.json'

dados_hospedagem = pd.read_json(path3)
dados_hospedagem = pd.json_normalize(dados_hospedagem['info_moveis'])
dados_hospedagem.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"

In [48]:
colunas = list(dados_hospedagem.columns)
dados_hospedagem = dados_hospedagem.explode(colunas[3:])

In [49]:
dados_hospedagem.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
0,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
0,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00

In [50]:
dados_hospedagem.reset_index(inplace=True, drop=True)

In [51]:
dados_hospedagem.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   str
 1   experiencia_local     3818 non-null   str
 2   max_hospedes          3818 non-null   str
 3   descricao_local       3818 non-null   str
 4   descricao_vizinhanca  3818 non-null   str
 5   quantidade_banheiros  3818 non-null   str
 6   quantidade_quartos    3818 non-null   str
 7   quantidade_camas      3818 non-null   str
 8   modelo_cama           3818 non-null   str
 9   comodidades           3818 non-null   str
 10  taxa_deposito         3818 non-null   str
 11  taxa_limpeza          3818 non-null   str
 12  preco                 3818 non-null   str
dtypes: str(13)
memory usage: 387.9 KB

In [52]:
colunas_int = ['quantidade_quartos', 'quantidade_banheiros', 'quantidade_camas']

dados_hospedagem['max_hospedes'] = dados_hospedagem['max_hospedes'].astype(int)

dados_hospedagem['avaliacao_geral'] = dados_hospedagem['avaliacao_geral'].astype(float)

dados_hospedagem[colunas_int] = dados_hospedagem[colunas_int].astype(int)

In [53]:
dados_hospedagem[['taxa_deposito', 'taxa_limpeza', 'preco']] = dados_hospedagem[['taxa_deposito', 'taxa_limpeza', 'preco']].map(lambda x: x.replace('$', '').replace('.', '').replace(',', ''))
dados_hospedagem[['taxa_deposito', 'taxa_limpeza', 'preco']] = dados_hospedagem[['taxa_deposito', 'taxa_limpeza', 'preco']].astype(float)

dados_hospedagem.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,11000.0
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,4500.0
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,5500.0
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,2000.0,5200.0
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",0.0,1500.0,8500.0

In [54]:
dados_hospedagem.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,11000.0
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,4500.0
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,5500.0
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,2000.0,5200.0
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",0.0,1500.0,8500.0

In [55]:
dados_hospedagem['descricao_local'] = dados_hospedagem['descricao_local'].str.replace('[^a-zA-Z0-9\-\'\,]','',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\-'
<>:1: SyntaxWarning: invalid escape sequence '\-'
C:\Users\eneto\AppData\Local\Temp\ipykernel_63436\1227285004.py:1: SyntaxWarning: invalid escape sequence '\-'
  dados_hospedagem['descricao_local'] = dados_hospedagem['descricao_local'].str.replace('[^a-zA-Z0-9\-\'\,]','',regex=True)

In [56]:
dados_hospedagem.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,Thiscleanandcomfortableonebedroomsitsrightacro...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,11000.0
1,10.0,--,1,OurcenturyoldUpperQueenAnnehouseislocatednearb...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,4500.0
2,10.0,--,1,Cozyroomintwo-bedroomapartmentalongthelowerPhi...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,5500.0
3,10.0,--,1,VerylovelyandcozyroomforoneConvenientlylocated...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,2000.0,5200.0
4,10.0,--,1,TheStudioatMibbettHollow'isinaBeautifulHousebo...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",0.0,1500.0,8500.0

In [57]:
dados_hospedagem['comodidades'] = dados_hospedagem['comodidades'].str.replace('\{|}|\"', '', regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\{'
<>:1: SyntaxWarning: invalid escape sequence '\{'
C:\Users\eneto\AppData\Local\Temp\ipykernel_63436\2981169347.py:1: SyntaxWarning: invalid escape sequence '\{'
  dados_hospedagem['comodidades'] = dados_hospedagem['comodidades'].str.replace('\{|}|\"', '', regex=True)

In [58]:
dados_hospedagem['comodidades'] = dados_hospedagem['comodidades'].str.split(',')

In [59]:
dados_hospedagem.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,Thiscleanandcomfortableonebedroomsitsrightacro...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,0.0,11000.0
1,10.0,--,1,OurcenturyoldUpperQueenAnnehouseislocatednearb...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,4500.0
2,10.0,--,1,Cozyroomintwo-bedroomapartmentalongthelowerPhi...,The convenience of being in Seattle but on the...,1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,5500.0
3,10.0,--,1,VerylovelyandcozyroomforoneConvenientlylocated...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,2000.0,5200.0
4,10.0,--,1,TheStudioatMibbettHollow'isinaBeautifulHousebo...,--,1,1,1,Real Bed,"[Wireless Internet, Kitchen, Free Parking on P...",0.0,1500.0,8500.0

In [60]:
dados_hospedagem['descricao_vizinhanca'] = dados_hospedagem['descricao_vizinhanca'].str.lower()

In [61]:
dados_hospedagem['descricao_vizinhanca'] = dados_hospedagem['descricao_vizinhanca'].str.replace('[^a-zA-Z0-9\-\']', '', regex=True)
dados_hospedagem['descricao_vizinhanca'] = dados_hospedagem['descricao_vizinhanca'].str.replace('(?<!\w)-(?!\w)', '', regex=True)
dados_hospedagem['descricao_vizinhanca'] = dados_hospedagem['descricao_vizinhanca'].str.split()

<>:1: SyntaxWarning: invalid escape sequence '\-'
<>:2: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\-'
<>:2: SyntaxWarning: invalid escape sequence '\w'
C:\Users\eneto\AppData\Local\Temp\ipykernel_63436\1131168321.py:1: SyntaxWarning: invalid escape sequence '\-'
  dados_hospedagem['descricao_vizinhanca'] = dados_hospedagem['descricao_vizinhanca'].str.replace('[^a-zA-Z0-9\-\']', '', regex=True)
C:\Users\eneto\AppData\Local\Temp\ipykernel_63436\1131168321.py:2: SyntaxWarning: invalid escape sequence '\w'
  dados_hospedagem['descricao_vizinhanca'] = dados_hospedagem['descricao_vizinhanca'].str.replace('(?<!\w)-(?!\w)', '', regex=True)

In [62]:
dados_hospedagem.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,Thiscleanandcomfortableonebedroomsitsrightacro...,[lowerqueenanneisneartheseattlecenterspaceneed...,1,1,1,Real Bed,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,0.0,11000.0
1,10.0,--,1,OurcenturyoldUpperQueenAnnehouseislocatednearb...,[upperqueenanneisareallypleasantuniquelittleoa...,1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,4500.0
2,10.0,--,1,Cozyroomintwo-bedroomapartmentalongthelowerPhi...,[theconvenienceofbeinginseattlebutonthewestslo...,1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,5500.0
3,10.0,--,1,VerylovelyandcozyroomforoneConvenientlylocated...,[ballardislovelyvibrantandoneofthemostrapidlyg...,1,1,1,Pull-out Sofa,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,2000.0,5200.0
4,10.0,--,1,TheStudioatMibbettHollow'isinaBeautifulHousebo...,[],1,1,1,Real Bed,"[Wireless Internet, Kitchen, Free Parking on P...",0.0,1500.0,8500.0

In [63]:
dados.head()

  Data de venda             Cliente  Valor da compra
0    2022-06-06     @ANA _LUCIA 321           8365.0
1    2022-06-06  DieGO ARMANDIU 210          57333.0
2    2022-06-06  DieGO ARMANDIU 210           3928.0
3    2022-06-06  DieGO ARMANDIU 210          51234.0
4    2022-07-06  Isabely JOanes 738          82531.0

In [64]:
dados['Cliente'] = dados['Cliente'].str.lower().replace('[^a-zA-Zá-úÁ-Ú ]','',regex=True)

In [65]:
dados.head()

  Data de venda          Cliente  Valor da compra
0    2022-06-06       ana lucia            8365.0
1    2022-06-06  diego armandiu           57333.0
2    2022-06-06  diego armandiu            3928.0
3    2022-06-06  diego armandiu           51234.0
4    2022-07-06  isabely joanes           82531.0

In [66]:
dados2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),2022-01-06,2022-05-06,10000.0
1,A101 (blocoAP),2022-01-07,2022-03-07,25000.0
2,A102 (blocoAP),2022-02-06,2022-02-06,11000.0
3,A102 (blocoAP),2022-02-07,2022-06-07,26000.0
4,B201 (blocoAP),2022-03-06,2022-07-06,12000.0
5,B201 (blocoAP),2022-03-07,2022-03-07,27000.0
6,B202 (blocoAP),2022-04-06,2022-07-06,13000.0
7,B202 (blocoAP),2022-04-07,2022-05-07,28000.0
8,C301 (blocoAP),2022-05-06,2022-10-06,14000.0
9,C301 (blocoAP),2022-05-07,2022-09-07,29000.0
10,C302 (blocoAP),2022-06-06,2022-08-06,15000.0
11,C302 (blocoAP),2022-06-07,2022-12-07,12000.0
12,D401 (blocoAP),2022-07-06,2022-07-06,16000.0
13,D401 (blocoAP),2022-07-07,2022-09-07,13000.0
14,D402 (blocoAP),2022-08-06,2022-10-06,17000.0
15,D402 (blocoAP),2022-08-07,2022-07-14,14000.0
16,E501 (blocoAP),2022-09-06,2022-10-06,18000.0
17,E501 (blocoAP),2022-09-07,2022-09-07,15000.0
18,E502 (blocoAP),2022-10-06,2022-06-16,19000.0
19,E502 (blocoAP),2022-10-07,2022-12-07,16000.0
20,F601 (blocoAP),2022-11-06,2022-06-17,20000.0
21,F601 (blocoAP),2022-11-07,2022-07-13,10000.0
22,F602 (blocoAP),2022-12-06,2022-06-15,21000.0
23,F602 (blocoAP),2022-12-07,2022-12-07,11000.0
24,G701 (blocoAP),2022-06-13,2022-06-19,22000.0
25,G701 (blocoAP),2022-07-13,2022-07-20,12000.0
26,G702 (blocoAP),2022-06-14,2022-06-15,23000.0
27,G702 (blocoAP),2022-07-14,2022-07-17,21000.0
28,H801 (blocoAP),2022-06-15,2022-06-18,24000.0
29,H801 (blocoAP),2022-07-15,2022-07-16,22000.0

In [67]:
dados2['apartamento'] = dados2['apartamento'].str.replace('\(blocoAP\)', '', regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\('
<>:1: SyntaxWarning: invalid escape sequence '\('
C:\Users\eneto\AppData\Local\Temp\ipykernel_63436\2920945497.py:1: SyntaxWarning: invalid escape sequence '\('
  dados2['apartamento'] = dados2['apartamento'].str.replace('\(blocoAP\)', '', regex=True)

In [68]:
dados2

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0        A101                  2022-01-06         2022-05-06        10000.0
1        A101                  2022-01-07         2022-03-07        25000.0
2        A102                  2022-02-06         2022-02-06        11000.0
3        A102                  2022-02-07         2022-06-07        26000.0
4        B201                  2022-03-06         2022-07-06        12000.0
5        B201                  2022-03-07         2022-03-07        27000.0
6        B202                  2022-04-06         2022-07-06        13000.0
7        B202                  2022-04-07         2022-05-07        28000.0
8        C301                  2022-05-06         2022-10-06        14000.0
9        C301                  2022-05-07         2022-09-07        29000.0
10       C302                  2022-06-06         2022-08-06        15000.0
11       C302                  2022-06-07         2022-12-07        12000.0
12       D401                  2022-07-06         2022-07-06        16000.0
13       D401                  2022-07-07         2022-09-07        13000.0
14       D402                  2022-08-06         2022-10-06        17000.0
15       D402                  2022-08-07         2022-07-14        14000.0
16       E501                  2022-09-06         2022-10-06        18000.0
17       E501                  2022-09-07         2022-09-07        15000.0
18       E502                  2022-10-06         2022-06-16        19000.0
19       E502                  2022-10-07         2022-12-07        16000.0
20       F601                  2022-11-06         2022-06-17        20000.0
21       F601                  2022-11-07         2022-07-13        10000.0
22       F602                  2022-12-06         2022-06-15        21000.0
23       F602                  2022-12-07         2022-12-07        11000.0
24       G701                  2022-06-13         2022-06-19        22000.0
25       G701                  2022-07-13         2022-07-20        12000.0
26       G702                  2022-06-14         2022-06-15        23000.0
27       G702                  2022-07-14         2022-07-17        21000.0
28       H801                  2022-06-15         2022-06-18        24000.0
29       H801                  2022-07-15         2022-07-16        22000.0

In [69]:
import pandas as pd

moveis_disponiveis = pd.read_json('moveis_disponiveis.json')

In [70]:
moveis_disponiveis['data'] = pd.to_datetime(moveis_disponiveis['data'])
moveis_disponiveis.info()

<class 'pandas.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  datetime64[us]
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  str
dtypes: bool(1), datetime64[us](1), int64(1), str(1)
memory usage: 11.5 MB

In [71]:
moveis_disponiveis['preco'].astype(str)
moveis_disponiveis['preco'].fillna(0.0)

0             0.0
1             0.0
2             0.0
3             0.0
4             0.0
           ...
364995    $140.00
364996    $140.00
364997    $140.00
364998    $140.00
364999        0.0
Name: preco, Length: 365000, dtype: object

In [72]:
moveis_disponiveis['preco'] = pd.to_numeric(moveis_disponiveis['preco'].str.replace('$','').replace(',','.'), errors='coerce')
moveis_disponiveis['preco'] = moveis_disponiveis['preco'].fillna(0.0)

In [73]:
moveis_disponiveis['preco'].astype(float)
moveis_disponiveis.info()

<class 'pandas.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  datetime64[us]
 2   vaga_disponivel  365000 non-null  bool
 3   preco            365000 non-null  float64
dtypes: bool(1), datetime64[us](1), float64(1), int64(1)
memory usage: 11.5 MB

In [95]:
total_compras = dados.groupby(['Cliente'])['Valor da compra'].sum()

In [96]:
total_compras

Cliente
ana lucia            8365.0
diego armandiu     112495.0
isabely joanes     232930.0
joão gabriel        38634.0
julya meireles     129247.0
maria julia        208665.0
paulo castro        89916.0
pedro pasco         31115.0
thiago fritzz       88524.0
Name: Valor da compra, dtype: float64

In [88]:
dados2.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     str
 1   datas_combinadas_pagamento  30 non-null     datetime64[ns]
 2   datas_de_pagamento          30 non-null     datetime64[ns]
 3   valor_aluguel               30 non-null     float64
dtypes: datetime64[ns](2), float64(1), str(1)
memory usage: 1.1 KB

In [91]:
dados2['atraso'] = (dados2['datas_de_pagamento'] - dados2['datas_combinadas_pagamento']).dt.days

In [93]:
media_atraso = dados2.groupby(['apartamento'])['atraso'].mean()

In [94]:
media_atraso

apartamento
A101      89.5
A102      60.0
B201      61.0
B202      60.5
C301     138.0
C302     122.0
D401      31.0
D402      18.5
E501      15.0
E502     -25.5
F601    -129.5
F602     -87.0
G701       6.5
G702       2.0
H801       2.0
Name: atraso, dtype: float64