In [1]:
import pandas as pd

In [92]:
path = 'moveis_disponiveis.json'
path2 = 'dados_hospedagem.json'

moveis_disponiveis = pd.read_json(path)
dados_hospedagem = pd.read_json(path2)

In [93]:
dados_hospedagem_normalizado = pd.json_normalize(dados_hospedagem['info_moveis'])

<ul>
    <li>avaliacao_geral: refere-se à média de notas dadas para a avaliação da hospedagem no imóvel.</li>
    <li>experiencia_local: descreve as experiências oferecidas durante a hospedagem no imóvel.</li>
    <li>max_hospedes: informa a quantidade máxima de hóspedes que o local permite.</li>
    <li>descricao_local: descreve o imóvel.</li>
    <li>descricao_vizinhanca: descreve a vizinhança ao redor do imóvel.</li>
    <li>quantidade_banheiros: informa a quantidade de banheiros disponíveis.</li>
    <li>quantidade_quartos: informa a quantidade de quartos disponíveis.</li>
    <li>quantidade_camas: informa a quantidade de camas disponíveis.</li>
    <li>modelo_cama: informa o modelo de cama oferecido.</li>
    <li>comodidades: informa as comodidades oferecidas pelo imóvel.</li>
    <li>taxa_deposito: informa a taxa de depósito mínima para segurança de hospedagem.</li>
    <li>taxa_limpeza: informa a taxa cobrada para o serviço de limpeza.</li>
    <li>preco: refere-se ao preço base a ser cobrado pela diária no imóvel.</li>
</ul>

In [94]:
dados_hospedagem_normalizado

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,nan,--,5,[Our cozy little bungalow is the perfect place...,[The Queen Anne neighborhood is one of the mos...,"[1, 3, 2, 2, 2, 1, 2, 1, 1, 1, 2, 3, 2, 2, 2, ...","[2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, ...","[3, 2, 2, 3, 3, 2, 3, 2, 2, 3, 3, 3, 2, 3, 2, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{""Cable TV"",""Wireless Internet"",Kitchen,""Free...","[$250.00, $200.00, $0, $0, $0, $200.00, $350.0...","[$35.00, $50.00, $100.00, $100.00, $0, $30.00,...","[$150.00, $200.00, $143.00, $150.00, $350.00, ..."
66,nan,--,6,[Bright clean 2 bedroom 1 bath appartment in t...,[Ballard is the most interesting and ecclectic...,"[1, 1, 3, 2, 1, 3, 2, 2, 1, 2, 2, 2, 1, 2, 1, ...","[2, 3, 3, 2, 2, 3, 2, 3, 2, 2, 2, 2, 4, 3, 3, ...","[3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 2, 4, 4, 3, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",K...","[$200.00, $200.00, $100.00, $0, $0, $750.00, $...","[$0, $0, $100.00, $0, $75.00, $140.00, $112.00...","[$99.00, $185.00, $250.00, $200.00, $275.00, $..."
67,nan,--,7,[Beautiful end-unit townhome with lots of dayl...,"[Cherry blossoms (Sakura) in the spring, every...","[4, 3, 1, 2, 2, 1, 2, 1, 2, 2]","[3, 4, 3, 3, 3, 3, 3, 3, 3, 4]","[3, 5, 1, 5, 3, 2, 3, 4, 4, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$750.00, $350.00, $500.00, $500.00, $0, $200....","[$300.00, $90.00, $250.00, $100.00, $109.00, $...","[$218.00, $350.00, $450.00, $149.00, $99.00, $..."
68,nan,--,8,[Heart of Ballard new townhome with 4 BRs + ba...,"[--, --, The suite is conveniently located off...","[2, 2, 3, 1, 1, 2, 1, 3, 2, 1, 2, 1, 2, 2, 2, ...","[4, 2, 3, 4, 3, 3, 4, 4, 3, 5, 2, 3, 3, 4, 5, ...","[4, 4, 3, 3, 5, 5, 5, 5, 3, 5, 4, 5, 5, 4, 1, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",""Air Conditi...","[$500.00, $150.00, $250.00, $800.00, $0, $500....","[$50.00, $85.00, $150.00, $75.00, $100.00, $80...","[$275.00, $199.00, $400.00, $325.00, $300.00, ..."
69,nan,--,9,[This business-themed modern home features: *...,[Your hosts made Madison Valley their home whe...,"[2, 1]","[3, 4]","[6, 6]","[Real Bed, Real Bed]","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00, $500.00]","[$150.00, $0]","[$250.00, $350.00]"

In [95]:
colunas = list(dados_hospedagem_normalizado.columns)
colunas

['avaliacao_geral',
 'experiencia_local',
 'max_hospedes',
 'descricao_local',
 'descricao_vizinhanca',
 'quantidade_banheiros',
 'quantidade_quartos',
 'quantidade_camas',
 'modelo_cama',
 'comodidades',
 'taxa_deposito',
 'taxa_limpeza',
 'preco']

In [96]:
dados_hospedagem_normalizado = dados_hospedagem_normalizado.explode(colunas[3:])
dados_hospedagem_normalizado

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
0,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
0,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
68,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
68,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
69,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
69,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

In [97]:
dados_hospedagem_normalizado.reset_index(inplace=True, drop=True)
dados_hospedagem_normalizado

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3813,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
3814,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
3815,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
3816,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
3817,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

In [98]:
dados_hospedagem_normalizado.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   str
 1   experiencia_local     3818 non-null   str
 2   max_hospedes          3818 non-null   str
 3   descricao_local       3818 non-null   str
 4   descricao_vizinhanca  3818 non-null   str
 5   quantidade_banheiros  3818 non-null   str
 6   quantidade_quartos    3818 non-null   str
 7   quantidade_camas      3818 non-null   str
 8   modelo_cama           3818 non-null   str
 9   comodidades           3818 non-null   str
 10  taxa_deposito         3818 non-null   str
 11  taxa_limpeza          3818 non-null   str
 12  preco                 3818 non-null   str
dtypes: str(13)
memory usage: 387.9 KB

In [99]:
import numpy as np

In [100]:
dados_hospedagem_normalizado['max_hospedes'] = dados_hospedagem_normalizado['max_hospedes'].astype(int)

In [101]:
dados_hospedagem_normalizado.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   str
 1   experiencia_local     3818 non-null   str
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   str
 4   descricao_vizinhanca  3818 non-null   str
 5   quantidade_banheiros  3818 non-null   str
 6   quantidade_quartos    3818 non-null   str
 7   quantidade_camas      3818 non-null   str
 8   modelo_cama           3818 non-null   str
 9   comodidades           3818 non-null   str
 10  taxa_deposito         3818 non-null   str
 11  taxa_limpeza          3818 non-null   str
 12  preco                 3818 non-null   str
dtypes: int64(1), str(12)
memory usage: 387.9 KB

In [102]:
col_numericas = ['quantidade_banheiros', 'quantidade_quartos', 'quantidade_camas']

dados_hospedagem_normalizado[col_numericas] = dados_hospedagem_normalizado[col_numericas].astype(int)

In [103]:
dados_hospedagem_normalizado.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   str
 1   experiencia_local     3818 non-null   str
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   str
 4   descricao_vizinhanca  3818 non-null   str
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   str
 9   comodidades           3818 non-null   str
 10  taxa_deposito         3818 non-null   str
 11  taxa_limpeza          3818 non-null   str
 12  preco                 3818 non-null   str
dtypes: int64(4), str(9)
memory usage: 387.9 KB

In [104]:
dados_hospedagem_normalizado['avaliacao_geral'] = dados_hospedagem_normalizado['avaliacao_geral'].astype(float)

In [105]:
dados_hospedagem_normalizado.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   str
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   str
 4   descricao_vizinhanca  3818 non-null   str
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   str
 9   comodidades           3818 non-null   str
 10  taxa_deposito         3818 non-null   str
 11  taxa_limpeza          3818 non-null   str
 12  preco                 3818 non-null   str
dtypes: float64(1), int64(4), str(8)
memory usage: 387.9 KB

In [106]:
dados_hospedagem_normalizado['preco'] = dados_hospedagem_normalizado['preco'].astype(float)

ValueError: could not convert string to float: '$110.00'

In [107]:
dados_hospedagem_normalizado['preco'] = dados_hospedagem_normalizado['preco'].apply(lambda x: x.replace('$', '').replace(',', '').strip())

In [108]:
dados_hospedagem_normalizado['preco']

0       110.00
1        45.00
2        55.00
3        52.00
4        85.00
         ...
3813    299.00
3814    199.00
3815    400.00
3816    250.00
3817    350.00
Name: preco, Length: 3818, dtype: str

In [109]:
dados_hospedagem_normalizado['preco'] = dados_hospedagem_normalizado['preco'].astype(float)

In [111]:
dados_hospedagem_normalizado.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   str
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   str
 4   descricao_vizinhanca  3818 non-null   str
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   str
 9   comodidades           3818 non-null   str
 10  taxa_deposito         3818 non-null   str
 11  taxa_limpeza          3818 non-null   str
 12  preco                 3818 non-null   float64
dtypes: float64(2), int64(4), str(7)
memory usage: 387.9 KB

In [112]:
dados_hospedagem_normalizado[['taxa_deposito', 'taxa_limpeza']] = dados_hospedagem_normalizado[['taxa_deposito', 'taxa_limpeza']].map(lambda x: x.replace('$', '').replace(',', '').strip())

In [113]:
dados_hospedagem_normalizado.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   str
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   str
 4   descricao_vizinhanca  3818 non-null   str
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   str
 9   comodidades           3818 non-null   str
 10  taxa_deposito         3818 non-null   str
 11  taxa_limpeza          3818 non-null   str
 12  preco                 3818 non-null   float64
dtypes: float64(2), int64(4), str(7)
memory usage: 387.9 KB

In [114]:
dados_hospedagem_normalizado[['taxa_deposito', 'taxa_limpeza']] = dados_hospedagem_normalizado[['taxa_deposito', 'taxa_limpeza']].astype(float)

In [115]:
dados_hospedagem_normalizado.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   str
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   str
 4   descricao_vizinhanca  3818 non-null   str
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   str
 9   comodidades           3818 non-null   str
 10  taxa_deposito         3818 non-null   float64
 11  taxa_limpeza          3818 non-null   float64
 12  preco                 3818 non-null   float64
dtypes: float64(4), int64(4), str(5)
memory usage: 387.9 KB

In [118]:
dados_hospedagem_normalizado['descricao_local'] = dados_hospedagem_normalizado['descricao_local'].str.lower()

In [120]:
dados_hospedagem_normalizado.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,this clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,110.0
1,10.0,--,1,our century old upper queen anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,45.0
2,10.0,--,1,cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,55.0
3,10.0,--,1,very lovely and cozy room for one. convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,20.0,52.0
4,10.0,--,1,the “studio at mibbett hollow' is in a beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",0.0,15.0,85.0

In [121]:
dados_hospedagem_normalizado['descricao_local'][3169]

"built, run and supported by seattle tech and start up veterans, grokhome's focus is to create a supportive environment for smart people working on interesting projects, start ups and more. this listing is an upper bunk, in a 2-person shared room. *note: this fall, there will be major renovations happening on one kitchen and bathroom at a time. there will always be two other working kitchens and two working bathrooms in the house. we'll work to minimize the impact these renovations have on your stay. **this listing is only available to those working in the tech/science space. live in a hacker house, and immerse yourself in the seattle tech scene. you can expect to be surrounded by smart people solving big problems or working on something fun. we have frequent demo nights, and love when our guests share something they are passionate about. if you're new to the city, our deep ties to the seattle tech scene can help you get involved. expand your network, develop your ideas, and learn somet"

In [127]:
dados_hospedagem_normalizado['descricao_local'] = dados_hospedagem_normalizado['descricao_local'].str.replace('[^a-zA-Z0-9\-\']', ' ', regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\-'
<>:1: SyntaxWarning: invalid escape sequence '\-'
C:\Users\eneto\AppData\Local\Temp\ipykernel_31348\3050940609.py:1: SyntaxWarning: invalid escape sequence '\-'
  dados_hospedagem_normalizado['descricao_local'] = dados_hospedagem_normalizado['descricao_local'].str.replace('[^a-zA-Z0-9\-\']', ' ', regex=True)

In [129]:
dados_hospedagem_normalizado['descricao_local'] = dados_hospedagem_normalizado['descricao_local'].str.replace('(?<!\w)-(?!\w)', ' ', regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
C:\Users\eneto\AppData\Local\Temp\ipykernel_31348\407678080.py:1: SyntaxWarning: invalid escape sequence '\w'
  dados_hospedagem_normalizado['descricao_local'] = dados_hospedagem_normalizado['descricao_local'].str.replace('(?<!\w)-(?!\w)', ' ', regex=True)

In [132]:
dados_hospedagem_normalizado['descricao_local'] = dados_hospedagem_normalizado['descricao_local'].str.split()
dados_hospedagem_normalizado.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,NaN,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,110.0
1,10.0,--,1,NaN,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,45.0
2,10.0,--,1,NaN,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,55.0
3,10.0,--,1,NaN,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,20.0,52.0
4,10.0,--,1,NaN,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",0.0,15.0,85.0

In [134]:
dados_hospedagem_normalizado['comodidades'] = dados_hospedagem_normalizado['comodidades'].str.replace('\{|}|\"','',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\{'
<>:1: SyntaxWarning: invalid escape sequence '\{'
C:\Users\eneto\AppData\Local\Temp\ipykernel_31348\1156408043.py:1: SyntaxWarning: invalid escape sequence '\{'
  dados_hospedagem_normalizado['comodidades'] = dados_hospedagem_normalizado['comodidades'].str.replace('\{|}|\"','',regex=True)

In [136]:
dados_hospedagem_normalizado['comodidades'] = dados_hospedagem_normalizado['comodidades'].str.split(',')

In [137]:
dados_hospedagem_normalizado.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,NaN,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,0.0,110.0
1,10.0,--,1,NaN,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,45.0
2,10.0,--,1,NaN,The convenience of being in Seattle but on the...,1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,55.0
3,10.0,--,1,NaN,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,20.0,52.0
4,10.0,--,1,NaN,--,1,1,1,Real Bed,"[Wireless Internet, Kitchen, Free Parking on P...",0.0,15.0,85.0

In [138]:
dados_hospedagem_normalizado.info()

<class 'pandas.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   str
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       0 non-null      object
 4   descricao_vizinhanca  3818 non-null   str
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   str
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   float64
 11  taxa_limpeza          3818 non-null   float64
 12  preco                 3818 non-null   float64
dtypes: float64(4), int64(4), object(2), str(3)
memory usage: 387.9+ KB

In [142]:
moveis_disponiveis = pd.read_json('moveis_disponiveis.json')
moveis_disponiveis.head()

    id        data  vaga_disponivel preco
0  857  2016-01-04            False   NaN
1  857  2016-01-05            False   NaN
2  857  2016-01-06            False   NaN
3  857  2016-01-07            False   NaN
4  857  2016-01-08            False   NaN

In [143]:
moveis_disponiveis.info()

<class 'pandas.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  str
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  str
dtypes: bool(1), int64(1), str(2)
memory usage: 11.5 MB

In [146]:
moveis_disponiveis['data'] = pd.to_datetime(moveis_disponiveis['data'])

In [147]:
moveis_disponiveis.info()

<class 'pandas.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  datetime64[us]
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  str
dtypes: bool(1), datetime64[us](1), int64(1), str(1)
memory usage: 11.5 MB

In [148]:
moveis_disponiveis.head()

    id       data  vaga_disponivel preco
0  857 2016-01-04            False   NaN
1  857 2016-01-05            False   NaN
2  857 2016-01-06            False   NaN
3  857 2016-01-07            False   NaN
4  857 2016-01-08            False   NaN

In [ ]:
moveis_disponiveis['data'].dt.strftime('%Y-%m')

0         2016-01
1         2016-01
2         2016-01
3         2016-01
4         2016-01
           ...
364995    2016-12
364996    2016-12
364997    2016-12
364998    2017-01
364999    2017-01
Name: data, Length: 365000, dtype: str

In [151]:
subset = moveis_disponiveis.groupby(moveis_disponiveis['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()

In [154]:
subset

data
2016-01    16543
2016-02    20128
2016-03    23357
2016-04    22597
2016-05    23842
2016-06    23651
2016-07    22329
2016-08    22529
2016-09    22471
2016-10    23765
2016-11    23352
2016-12    24409
2017-01     1574
Name: vaga_disponivel, dtype: int64